const LandingPageCards = [
  {
    id: 1,
    img: "/Images/download.jpeg",
    title: "headphones",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "headphones",
  },
  {
    id: 2,
    img: "/Images/download.jpeg",
    title: "headphones",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "headphones",
  },
  {
    id: 3,
    img: "/Images/download.jpeg",
    title: "oculus",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "oculus",
  },
  {
    id: 4,
    img: "/Images/download.jpeg",
    title: "laptop",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "laptop",
  },
  {
    id: 5,
    img: "/Images/download.jpeg",
    title: "headphones",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "headphones",
  },
  {
    id: 6,
    img: "/Images/download.jpeg",
    title: "headphones",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "headphones",
  },
  {
    id: 7,
    img: "/Images/download.jpeg",
    title: "watch",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "watch",
  },
  {
    id: 8,
    img: "/Images/download.jpeg",
    title: "watch",
    price: "899",
    desc: "lorem 23d dfdvdcdcdv",
    category: "featured",
    productName: "watch",
  },
];

export default LandingPageCards;
